# Generated by Django 5.0.6 on 2024-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutboxes',
            name='box_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
