# Generated by Django 5.0.6 on 2024-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_informationaboutboxes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationaboutboxes',
            name='img',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
