# Generated by Django 5.0.6 on 2024-05-14 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_alter_informationaboutboxes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationaboutboxes',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='informationaboutboxes',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AlterField(
            model_name='informationaboutboxes',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
