# Generated by Django 5.0.6 on 2024-05-14 11:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_informationaboutboxes_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='informationaboutboxes',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
