# Generated by Django 5.0.6 on 2024-05-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_informationaboutboxes_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='informationaboutboxes',
            managers=[
            ],
        ),
    ]
