# Generated by Django 5.0.6 on 2024-05-14 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_alter_informationaboutboxes_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='informationaboutboxes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationaboutboxes',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
